/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.listatelefonicaswingbd;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class MenuListaTelefonica extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuListaTelefonica.class.getName());

    /**
     * Creates new form MenuListaTelefonica
     */
    public MenuListaTelefonica() {
        initComponents();
        carregarTabela();

        contatosTable.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting() && contatosTable.getSelectedRow() != -1) {
                int linha = contatosTable.getSelectedRow();

                idTextField.setText(contatosTable.getValueAt(linha, 0).toString());
                nomeTextField.setText(contatosTable.getValueAt(linha, 1).toString());
                emailTextField.setText(contatosTable.getValueAt(linha, 2).toString());
                telefoneTextField.setText(contatosTable.getValueAt(linha, 3).toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camposPanel = new javax.swing.JPanel();
        telefoneTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        campoBotoesPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        rmvButton = new javax.swing.JButton();
        altButton = new javax.swing.JButton();
        limpButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        contatosPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contatosTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista Telefônica");
        setResizable(false);

        telefoneTextField.addActionListener(this::telefoneTextFieldActionPerformed);

        idTextField.setEditable(false);
        idTextField.setToolTipText("");
        idTextField.addActionListener(this::idTextFieldActionPerformed);

        addButton.setText("Adicionar");
        addButton.addActionListener(this::addButtonActionPerformed);

        rmvButton.setText("Remover");
        rmvButton.addActionListener(this::rmvButtonActionPerformed);

        altButton.setText("Atualizar");
        altButton.addActionListener(this::altButtonActionPerformed);

        limpButton.setText("Limpar");
        limpButton.addActionListener(this::limpButtonActionPerformed);

        javax.swing.GroupLayout campoBotoesPanelLayout = new javax.swing.GroupLayout(campoBotoesPanel);
        campoBotoesPanel.setLayout(campoBotoesPanelLayout);
        campoBotoesPanelLayout.setHorizontalGroup(
            campoBotoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoBotoesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        campoBotoesPanelLayout.setVerticalGroup(
            campoBotoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campoBotoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(campoBotoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rmvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Lista Telefônica");

        idLabel.setText("ID");

        emailLabel.setText("E-mail");

        nomeLabel.setText("Nome");

        telefoneLabel.setText("Telefone");

        javax.swing.GroupLayout camposPanelLayout = new javax.swing.GroupLayout(camposPanel);
        camposPanel.setLayout(camposPanelLayout);
        camposPanelLayout.setHorizontalGroup(
            camposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campoBotoesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tituloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(camposPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(camposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camposPanelLayout.createSequentialGroup()
                        .addGroup(camposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField)
                            .addComponent(nomeTextField)
                            .addComponent(emailTextField)
                            .addComponent(telefoneTextField))
                        .addContainerGap())
                    .addGroup(camposPanelLayout.createSequentialGroup()
                        .addGroup(camposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        camposPanelLayout.setVerticalGroup(
            camposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, camposPanelLayout.createSequentialGroup()
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idLabel)
                .addGap(2, 2, 2)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeLabel)
                .addGap(2, 2, 2)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel)
                .addGap(2, 2, 2)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneLabel)
                .addGap(2, 2, 2)
                .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoBotoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contatosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "E-mail", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(contatosTable);
        if (contatosTable.getColumnModel().getColumnCount() > 0) {
            contatosTable.getColumnModel().getColumn(0).setResizable(false);
            contatosTable.getColumnModel().getColumn(1).setResizable(false);
            contatosTable.getColumnModel().getColumn(2).setResizable(false);
            contatosTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout contatosPanelLayout = new javax.swing.GroupLayout(contatosPanel);
        contatosPanel.setLayout(contatosPanelLayout);
        contatosPanelLayout.setHorizontalGroup(
            contatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        contatosPanelLayout.setVerticalGroup(
            contatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatosPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(camposPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(camposPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (nomeTextField.getText().isEmpty() || emailTextField.getText().isEmpty() || telefoneTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira os valores nos campos!");
            return;
        }

        ListaTelefonica contato = new ListaTelefonica();
        contato.setNome(nomeTextField.getText());
        contato.setEmail(emailTextField.getText());
        contato.setTelefone(telefoneTextField.getText());

        DAOListaTelefonica dao = new DAOListaTelefonica();
        dao.inserirContato(contato);

        carregarTabela();
        limparCampos();
    }//GEN-LAST:event_addButtonActionPerformed

    private void rmvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvButtonActionPerformed
        if (idTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione um contato para excluir!");
            return;
        }

        ListaTelefonica contato = new ListaTelefonica();
        contato.setId(Integer.parseInt(idTextField.getText()));

        DAOListaTelefonica dao = new DAOListaTelefonica();
        dao.excluirContato(contato);

        carregarTabela();
        limparCampos();
    }//GEN-LAST:event_rmvButtonActionPerformed

    private void altButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altButtonActionPerformed
        if (idTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione um contato para atualizar!");
            return;
        }

        ListaTelefonica contato = new ListaTelefonica();
        contato.setId(Integer.parseInt(idTextField.getText()));
        contato.setNome(nomeTextField.getText());
        contato.setEmail(emailTextField.getText());
        contato.setTelefone(telefoneTextField.getText());

        DAOListaTelefonica dao = new DAOListaTelefonica();
        dao.atualizarContato(contato);

        carregarTabela();
        limparCampos();
    }//GEN-LAST:event_altButtonActionPerformed

    private void limpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_limpButtonActionPerformed

    // Carregando os dados para a tabela
    private void carregarTabela() {
        DAOListaTelefonica dao = new DAOListaTelefonica();
        List<ListaTelefonica> contatos = dao.listarContatos();

        String[] colunas = {"ID", "Nome", "E-mail", "Telefone"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

        for (ListaTelefonica c : contatos) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getTelefone()
            });
        }

        contatosTable.setModel(modelo);
    }

    private void limparCampos() {
        idTextField.setText("");
        nomeTextField.setText("");
        emailTextField.setText("");
        telefoneTextField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuListaTelefonica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton altButton;
    private javax.swing.JPanel campoBotoesPanel;
    private javax.swing.JPanel camposPanel;
    private javax.swing.JPanel contatosPanel;
    private javax.swing.JTable contatosTable;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton rmvButton;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JTextField telefoneTextField;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
